// <auto-generated />
namespace HospiceNiagara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class isActiveDeactivate_Activate_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isActiveDeactivate_Activate_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201504150124522_isActive-Deactivate_Activate_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
