// <auto-generated />
namespace HospiceNiagara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class reverteddatetodatetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reverteddatetodatetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201503231729089_reverted-date-to-datetype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
