// <auto-generated />
namespace HospiceNiagara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changes_02_reverted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_02_reverted));
        
        string IMigrationMetadata.Id
        {
            get { return "201503240053333_changes_02_reverted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
